### ISSUE TITLE
Wäre es möglich das du ein plugin machst für scene files to ?

### ISSUE THREAD

**Issue by lorgas** [topy/Flexget-Plugins#1]
Wäre es möglich das du ein plugin machst für scene files to ?

und frage nr.2 weißt du wie ich flexget alle episoden die in meiner serien sammlung (trakt.tv) noch fehlen, automatisch zu erkennen, suchen und zu jdownloader hinzu zu fügen ?

**Comment by topy** [comment]
Folgende Config beinhaltet Lösungen für deine beiden Anliegen:
https://github.com/crack00r/Flexget-Config
